### ISSUE TITLE
[UI/Browsers] Significant Lag Upon Opening Spawners/Browsers

### ISSUE THREAD

**Issue by steviegt6** [ScalarVector1/DragonLens#5] opened 2023-01-29 08:19 UTC
On my machine, the game outright freezes for a short while upon first opening the Item Spawner. This is likely due to item rendering not being culled, resulting in every item sprite attempting to be loaded immediately. Additional optimizations could be made by not calling `Terraria.Item::SetDefaults` on every item until items come into view.

**Comment by steviegt6** [comment] 2023-01-30 01:27
Relevant to all spawners.

**Comment by ScalarVector1** [comment] 2023-02-28 03:17
This is likely caused by blocking for asset loading due to the manual asset load calls. I'll need to make a correction to have them properly lazy-load

**Comment by ScalarVector1** [comment] 2023-05-02 14:11
Closing this as its become irrelevant due to background async asset loading

**Closed by ScalarVector1** 2023-05-02 14:11 UTC
